name: Deploy images final project
run-name: ${{ github.actor }} is deploying images üöÄ
on: 
  push:
    branches:
      - proyecto-final
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      #Pasos de informaci√≥n
      - run: echo "üéâ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "üêß This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "üîé The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "üí° The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "üñ•Ô∏è The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      #Deployment
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push API MLOPs
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./proyectoFinal/Dockerfile_api
          tags: ${{ secrets.DOCKERHUB_TAG }}/proyectofinal-mi_api:latest
      - name: Build and push Streamlit MLOPs
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./proyectoFinal/Dockerfile_streamlit
          tags: ${{ secrets.DOCKERHUB_TAG }}/proyectofinal-streamlit_app:latest
      - name: Build and push Jupyter MLOPs
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./proyectoFinal/Dockerfile_jupyter
          tags: ${{ secrets.DOCKERHUB_TAG }}/proyectofinal-jupyter:latest
      - name: Build and push MLFLOW MLOPs
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./proyectoFinal/Dockerfile_mlflow
          tags: ${{ secrets.DOCKERHUB_TAG }}/proyectofinal-mlflow_serv:latest
      - run: echo "üçè This job's status is ${{ job.status }}."

